# Generated by fusen: do not edit by hand

test_that("recup_url_flag works", {
  expect_true(inherits(recup_url_flag, "function"))
  
  expect_error(recup_url_flag("https://www.monsieur-des-drapeaux.com//inconnu.html"), regexp = "url country no valide")
})
