# WARNING - Generated by {fusen} from /dev/flat_flag.Rmd: do not edit by hand

test_that("sample_country works", {
  expect_true(inherits(sample_country, "function")) 
  tbl <- tibble::tibble(url = "https://www.monsieur-des-drapeaux.com//bahamas.html",
                 country = "Bahamas" )
  expect_is(sample_country(tbl),"list")
  expect_is(sample_country(tbl, url_flag = FALSE),"list")
  expect_equal(length(sample_country(tbl)),2)
  expect_error(sample_country(tbl,5), regexp = "length of vector country < n")
  })

