# Generated by fusen: do not edit by hand

#' country
#' 
#' a function that retrieves the list of countries available at the url "https://www.monsieur-des-drapeaux.com/drapeaux-du-monde.html"
#'
#' @importFrom httr GET content
#' @importFrom rvest html_nodes html_text html_children
#' @importFrom xml2 read_html
#' @importFrom stringr str_split str_replace str_detect
#' @importFrom dplyr %>% mutate filter select inner_join
#' @importFrom glue glue
#' @importFrom tibble tibble
#' @return a dataframe with name country and url
#' @export
#'
#' @examples
#' world <- country()
#' head(world)
country <- function() {

      url <- GET("https://www.monsieur-des-drapeaux.com/drapeaux-du-monde.html") %>% 
    content(as = "text", encoding = "utf-8") %>% 
    read_html() %>% 
    html_nodes("li") %>% 
      html_children() 
    
    t1 <- url %>% 
      html_attr("href")

    t2 <- url %>% 
      html_text()
    
    # country delete:
    t3 <- url %>% 
       html_children() %>%  
       html_attr("class")
    
    t4 <- url %>% 
       html_children() %>%  
       html_text()
    
    t5 <- url %>% 
       html_children() %>%  
       html_attr("role")

    t <-  tibble(test = t3, country = t4, test2 = t5)%>%
      filter( is.na(test) &  is.na(test2)) %>% 
      filter( country !="") 
        
     tab<- tibble(url = t1, country = t2) %>% 
       filter(str_detect(url, pattern = "^/")) %>% 
        filter(str_detect(url, pattern = "html$")) %>% 
        filter( country!= "")
     
     tab1 <- tab %>% 
       inner_join(t, by ="country") %>%
       select(-test, -test2) %>% 
        mutate(url = glue::glue("https://www.monsieur-des-drapeaux.com/{url}"))

     return(tab1)
    
}
