# WARNING - Generated by {fusen} from /dev/flat_flag.Rmd: do not edit by hand

#' Recuperation url flag
#' 
#' Recuperation of url flag for a country
#' @param country the name of a country
#' @importFrom stringr str_extract
#' @importFrom httr GET status_code
#' @importFrom rvest html_elements html_attr
#' @importFrom xml2 read_html
#' @importFrom purrr pluck
#' @importFrom dplyr %>% 
#' 
#' @return url
#' 
#' @export
#' @examples
#' library(dplyr)
#' world <- country() %>%  
#'   sample_n(1) %>% 
#'   pull(url)
#' 
#' recup_url_flag(world)
recup_url_flag <- function(country){

  url <- GET(country)
  status <- url %>% 
     status_code()
  
if (status != "200") {stop("url country no valide")}

webpage1 <- read_html(url)

world <- webpage1 %>%
    html_elements('a[class="block product-name"]') %>% 
    purrr::pluck(1) %>% 
    html_attr("href") %>% 
    str_extract(pattern = "[0-9]+")

url <- glue::glue("https://node01.flagstat.net/media/catalog/product/big/{world}.png")

status <- GET(url) %>% 
     status_code()

if (status == '400') {stop("url flag no valide")}
return(url)
}
