# Generated by fusen: do not edit by hand

#' Recuperation url flag
#' 
#' Recuperation of url flag for a country
#' @param country the name of a country
#' @importFrom stringr str_to_lower str_replace_all str_extract
#' @importFrom httr GET content status_code
#' @importFrom rvest html_nodes html_attr
#' @importFrom xml2 read_html
#' @importFrom dplyr %>% 
#' 
#' @return url
#' 
#' @export
#' @examples
#' library(dplyr)
#' world <- country() %>%  
#'   sample_n(1) %>% 
#'   pull(url)
#' 
#' recup_url_flag(world)
recup_url_flag <- function(country){

  url <- GET(country)
  status <- url %>% 
     status_code()
  
if (status != "200") {stop("url country no valide")}

webpage1 <- url %>% 
    content(as = "text", encoding = "utf-8") %>% 
    read_html()

world <- webpage1 %>%
    html_nodes(xpath = '/html/body/div[2]/div[1]/div/div[2]/main/div/ul[2]/li[1]/div/div/h3/a') %>%
    html_attr("href") %>% 
    str_extract(pattern = "[0-9]+")

url <- glue::glue("https://node01.flagstat.net/media/catalog/product/big/{world}.png")

status <- GET(url) %>% 
     status_code()

if (status == '400') {stop("url flag no valide")}
return(url)
}
