# WARNING - Generated by {fusen} from /dev/flat_flag.Rmd: do not edit by hand

#' sample_country
#' 
#' A sample of country
#' @param list_country a dataframe of country /url
#' @param n a positive number, the number of items to choose from.
#' @param url_flag boolean TRUE if function must return the url of country
#' @importFrom stringr str_to_lower str_replace_all
#' @importFrom glue glue
#' @importFrom httr GET status_code
#' @importFrom dplyr %>% sample_n pull
#' @importFrom purrr map
#' @return list of name of a country and url of flag
#' 
#' @export
#' @examples
#' world <- country()
#' sample_country(world, n=3)
#' sample_country(world, n=3, url_flag = FALSE)
sample_country <- function(list_country, n = 1, url_flag = TRUE) {
  if (nrow(list_country) < n) {
    stop("length of vector country < n")
  }

  status <- 400

  while (!all(status == 200)) {
    list_sample <- list()

    tab <- sample_n(list_country, n)

    list_sample[["name"]] <- tab %>%
      pull(country)

    if (url_flag) {
      list_sample[["url_flag"]] <- tab %>%
        pull(url) %>%
        map(~ recup_url_flag(.))

      status <- list_sample[["url_flag"]] %>%
        map(~ status_code(GET(.)))
    } else {
      list_sample[["url_flag"]] <- ""
      status <- 200
    }
  }
  return(list_sample)
}
